In [ ]:
# If else statement
# example
score = int(input('Input Score: '))
if 90 <= score <= 100:
    grade = 'A'
elif 80 <= score < 90:
    grade = 'B'
elif 70 <= score < 80:
    grade = 'C'
elif 60 <= score < 70:
    grade = 'D'
else:
    grade = 'F'
print("Grade is " + grade)

In [ ]:
# Boolean example
bool(False)

In [ ]:
bool(13)

In [ ]:
bool(0.0)

In [ ]:
bool('apple')

In [ ]:
bool('')

In [ ]:
bool(0)

In [ ]:
bool([10,20])

In [ ]:
# and / or statement

In [ ]:
# filter statement
def GetBiggerThan20(i):
    return i > 20

L = [10, 25, 30]
IterL = filter(GetBiggerThan20, L)
for i in IterL:
    print("Item:{0}".format(i))

In [ ]:
# Importing modules
import os

In [ ]:
# Can list up functions available in specified module
dir(os)

In [ ]:
import math
dir(math)

In [ ]:
# 4 ways to import moudles (1st, 4th recommended)
# import <module>
# from <module> import <attirbute>
# from <module> import *
# import <module> as <alias>

In [ ]:
dir(__builtins__)
# No need to import

In [ ]:
# Many Modules which is availabe.. (Can see at summary txt file)

In [ ]:
# Printing output
import sys
sys.stdout.write("test")

In [ ]:
sys.stdout.write("pyo")

In [ ]:
msg = "Hello"
print(msg + " Daniel")
sys.stdout.write(msg + " Daniel\n")
sys.stdout.write("안녕하세요 ㅎㅎ")

In [ ]:
key = input("insert your name:")

In [ ]:
print(key)

In [ ]:
# !<os command>
!mkdir test2

In [ ]:
# / does not permitted in windows
!mkdir C:/Users/student/Desktop/multicamplus/multi-python/code/test3

In [ ]:
!mkdir C:\Users\student\Desktop\multicamplus\multi-python\code\test3

In [ ]:
f = open('test2/test.txt','w')

In [ ]:
print('file write test...', file = f)
f.close()

In [ ]:
f1 = open('test2/test.txt')
f1.read()

In [ ]:
f1.closed

In [ ]:
f1.close()

In [ ]:
############ NumPy
# ndarray
import numpy as np
data = np.random.randn(2,3) # row, column
print(data)

In [ ]:
# Broadcasting (elementwise)
data * 10

In [ ]:
# elementwise add
data + data

In [ ]:
# ndarray's row and column (since it is 2D array... in case of 1D array will show 1 dimensional shape)
data.shape

In [ ]:
# ndarray's type
data.dtype

In [ ]:
np.arange(1,3,1)

In [ ]:
np.arange(-10, -2, 2)

In [ ]:
# add elementwise
a = np.array([1,2])
b = np.array([1,2])
print(a+b)

In [ ]:
# elementwise multiplication
arr = np.array([1,2,3,4,5])
arr * 2

In [ ]:
# array inner product (dot product)
a = np.array([1,2,3,4,5])
b = np.array([2,4,6,8,10])
print(sum(a*b))

In [ ]:
### NumPy Practice

In [1]:
import numpy as np

In [2]:
data1 = [10,9.9, 9.8, 9.7, 11]

In [3]:
print(data1)

[10, 9.9, 9.8, 9.7, 11]


In [4]:
arr1 = np.array(data1)

In [5]:
print(arr1)

[ 10.    9.9   9.8   9.7  11. ]


In [6]:
print(arr1.shape)

(5,)


In [7]:
print(np.zeros( (3,5) ))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [8]:
print(np.zeros(5))

[ 0.  0.  0.  0.  0.]


In [9]:
print(np.ones(5))

[ 1.  1.  1.  1.  1.]


In [10]:
print(np.ones((3,5)))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [11]:
data2 = [[1, 3, 5], [2, 4, 6]]

In [12]:
print(data2)

[[1, 3, 5], [2, 4, 6]]


In [13]:
arr2 = np.array(data2)

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.array([1,2,3,4,5], dtype = np.int64)

In [20]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [21]:
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)

In [26]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [27]:
float_arr.dtype

dtype('float64')

In [33]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype = np.float64)

In [35]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype = np.float64)

In [36]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [37]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [38]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [39]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [41]:
arr1  * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [42]:
arr1 ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])