In [2]:
# If else statement
# example
score = int(input('Input Score: '))
if 90 <= score <= 100:
    grade = 'A'
elif 80 <= score < 90:
    grade = 'B'
elif 70 <= score < 80:
    grade = 'C'
elif 60 <= score < 70:
    grade = 'D'
else:
    grade = 'F'
print("Grade is " + grade)

Input Score: 90
Grade is A


In [3]:
# Boolean example
bool(False)

False

In [4]:
bool(13)

True

In [5]:
bool(0.0)

False

In [6]:
bool('apple')

True

In [7]:
bool('')

False

In [8]:
bool(0)

False

In [9]:
bool([10,20])

True

In [10]:
# and / or statement

In [11]:
# filter statement
def GetBiggerThan20(i):
    return i > 20

L = [10, 25, 30]
IterL = filter(GetBiggerThan20, L)
for i in IterL:
    print("Item:{0}".format(i))

Item:25
Item:30


In [15]:
# Importing modules
import os

In [13]:
# Can list up functions available in specified module
dir(os)

['DirEntry',
 'F_OK',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_Environ',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_putenv',
 '_unsetenv',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'errno',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fs

In [14]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [16]:
# 4 ways to import moudles (1st, 4th recommended)
# import <module>
# from <module> import <attirbute>
# from <module> import *
# import <module> as <alias>

In [17]:
dir(__builtins__)
# No need to import

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [20]:
# Many Modules which is availabe.. (Can see at summary txt file)

In [21]:
# Printing output
import sys
sys.stdout.write("test")

test

In [22]:
sys.stdout.write("pyo")

pyo

In [32]:
msg = "Hello"
print(msg + " Daniel")
sys.stdout.write(msg + " Daniel\n")
sys.stdout.write("안녕하세요 ㅎㅎ")

Hello Daniel
Hello Daniel
안녕하세요 ㅎㅎ

In [33]:
key = input("insert your name:")

insert your name:Sunny


In [34]:
print(key)

Sunny


In [35]:
# !<os command>
!mkdir test2

In [36]:
# / does not permitted in windows
!mkdir C:/Users/student/Desktop/multicamplus/multi-python/code/test3

명령 구문이 올바르지 않습니다.


In [37]:
!mkdir C:\Users\student\Desktop\multicamplus\multi-python\code\test3

In [38]:
f = open('test2/test.txt','w')

In [39]:
print('file write test...', file = f)
f.close()

In [43]:
f1 = open('test2/test.txt')
f1.read()

'file write test...\n'

In [44]:
f1.closed

False

In [45]:
f1.close()

In [46]:
############ NumPy
# ndarray
import numpy as np
data = np.random.randn(2,3) # row, column
print(data)

[[ 0.88086624  0.39889442  0.44312102]
 [-1.22586496 -0.73929746 -1.5352921 ]]


In [47]:
# Broadcasting (elementwise)
data * 10

array([[  8.8086624 ,   3.98894424,   4.43121021],
       [-12.25864957,  -7.39297463, -15.35292097]])

In [48]:
# elementwise add
data + data

array([[ 1.76173248,  0.79778885,  0.88624204],
       [-2.45172991, -1.47859493, -3.07058419]])

In [49]:
# ndarray's row and column (since it is 2D array... in case of 1D array will show 1 dimensional shape)
data.shape

(2, 3)

In [50]:
# ndarray's type
data.dtype

dtype('float64')

In [52]:
np.arange(1,3,1)

array([1, 2])

In [58]:
np.arange(-10, -2, 2)

array([-10,  -8,  -6,  -4])

In [59]:
a = np.array([1,2])
b = np.array([1,2])
print(a+b)

[2 4]


In [60]:
arr = np.array([1,2,3,4,5])
arr * 2

array([ 2,  4,  6,  8, 10])