In [1]:
import numpy as np

In [2]:
np.sin?

In [6]:
np.sqrt?

In [4]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
z = np.random.rand(10)

In [8]:
x

array([ 0.07994885,  0.41684538,  0.71746628,  0.14642389,  0.9297787 ,
        0.66287949,  0.15834475,  0.6942718 ,  0.73640571,  0.92372131])

In [9]:
y

array([ 0.05588238,  0.90116647,  0.62603041,  0.1283728 ,  0.77254208,
        0.56912128,  0.33996601,  0.93786597,  0.50280055,  0.89650979])

In [10]:
z

array([ 0.99530249,  0.60279259,  0.17302124,  0.21761145,  0.89267546,
        0.29310437,  0.5146648 ,  0.22196539,  0.8430442 ,  0.19449825])

In [11]:
np.maximum(x,y,z) 

array([ 0.07994885,  0.90116647,  0.71746628,  0.14642389,  0.9297787 ,
        0.66287949,  0.33996601,  0.93786597,  0.73640571,  0.92372131])

In [13]:
arr2 = np.random.randn(6,5) 
arr2

array([[-0.27289841, -1.79142746, -1.27676818, -1.83872404, -1.29671001],
       [-1.00406003, -1.8690602 ,  0.73271895,  0.11060222,  0.34985089],
       [-1.75573177,  0.20756977, -0.18949949, -1.21437485, -0.39034284],
       [ 1.32806498,  0.72599205,  0.62117916,  0.11090126,  0.84440616],
       [-0.16364706, -1.01446182, -1.22537205,  0.46176692,  0.16816007],
       [ 1.01700645,  0.19905617, -0.61212635,  1.02212426, -0.51700301]])

In [14]:
arr2.sum() 

-8.532808262666407

In [15]:
arr2.mean() 

-0.28442694208888025

In [16]:
arr2.sum(axis=0) 

array([-0.85126585, -3.54233149, -1.94986797, -1.34770422, -0.84163874])

In [17]:
arr2.sum(axis=1) 

array([-6.47652811, -1.67994817, -3.34237918,  3.63054362, -1.77355394,
        1.10905752])

In [18]:
arr2 > 0

array([[False, False, False, False, False],
       [False, False,  True,  True,  True],
       [False,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True, False,  True, False]], dtype=bool)

In [19]:
(arr2>0).sum() 

14

In [20]:
arr3 = np.random.randn(7) 
arr3

array([  1.89070074e+00,  -5.02637125e-01,  -4.55785167e-02,
         7.17518706e-01,   1.09955402e+00,  -1.43756950e+00,
         1.70841919e-03])

In [21]:
arr3.sort() 

In [22]:
arr3

array([ -1.43756950e+00,  -5.02637125e-01,  -4.55785167e-02,
         1.70841919e-03,   7.17518706e-01,   1.09955402e+00,
         1.89070074e+00])

In [23]:
np.sort(arr3) 

array([ -1.43756950e+00,  -5.02637125e-01,  -4.55785167e-02,
         1.70841919e-03,   7.17518706e-01,   1.09955402e+00,
         1.89070074e+00])

In [24]:
np.sort(arr3)[::-1] 

array([  1.89070074e+00,   1.09955402e+00,   7.17518706e-01,
         1.70841919e-03,  -4.55785167e-02,  -5.02637125e-01,
        -1.43756950e+00])

In [25]:
arr4 = np.random.randn(5,3)
arr4

array([[ 0.74510801, -0.19156068,  0.14801945],
       [ 0.56236519, -0.31026852, -0.75951696],
       [ 1.50715223,  2.80423801, -0.63835645],
       [-0.35475125, -1.96801212, -0.18981531],
       [-0.86364734, -0.87071971,  0.24854202]])

In [26]:
np.sort(arr4, axis=0) 

array([[-0.86364734, -1.96801212, -0.75951696],
       [-0.35475125, -0.87071971, -0.63835645],
       [ 0.56236519, -0.31026852, -0.18981531],
       [ 0.74510801, -0.19156068,  0.14801945],
       [ 1.50715223,  2.80423801,  0.24854202]])

In [27]:
np.sort(arr4, axis=1) 

array([[-0.19156068,  0.14801945,  0.74510801],
       [-0.75951696, -0.31026852,  0.56236519],
       [-0.63835645,  1.50715223,  2.80423801],
       [-1.96801212, -0.35475125, -0.18981531],
       [-0.87071971, -0.86364734,  0.24854202]])

In [28]:
np.sort(arr4)[::-1]

array([[-0.87071971, -0.86364734,  0.24854202],
       [-1.96801212, -0.35475125, -0.18981531],
       [-0.63835645,  1.50715223,  2.80423801],
       [-0.75951696, -0.31026852,  0.56236519],
       [-0.19156068,  0.14801945,  0.74510801]])

In [29]:
np.sort(arr4, axis=1)[::-1] 

array([[-0.87071971, -0.86364734,  0.24854202],
       [-1.96801212, -0.35475125, -0.18981531],
       [-0.63835645,  1.50715223,  2.80423801],
       [-0.75951696, -0.31026852,  0.56236519],
       [-0.19156068,  0.14801945,  0.74510801]])

In [30]:
np.sort(arr4, axis=0)[::-1] 

array([[ 1.50715223,  2.80423801,  0.24854202],
       [ 0.74510801, -0.19156068,  0.14801945],
       [ 0.56236519, -0.31026852, -0.18981531],
       [-0.35475125, -0.87071971, -0.63835645],
       [-0.86364734, -1.96801212, -0.75951696]])

In [31]:
names = np.array(["sunyoung", "pyo", "sunny", "sunyoung", "pyo", "sunny", "sunyoung"])
value = np.array([3,3,3,2,2,1,1,4,4])

In [32]:
np.unique(names) 

array(['pyo', 'sunny', 'sunyoung'],
      dtype='<U8')

In [33]:
np.unique(value)

array([1, 2, 3, 4])