In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 9.8, 9.7, 11]

In [3]:
data1

[10, 9.9, 9.8, 9.7, 11]

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([ 10. ,   9.9,   9.8,   9.7,  11. ])

In [6]:
arr1.shape

(5,)

In [7]:
np.zeros( ( 3,5)) 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [9]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [10]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
data2 = [ [1,2,3,4],[5,6,7,8]]  

In [12]:
arr2 = np.array(data2) 

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [17]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [18]:
arr.dtype

dtype('int64')

In [19]:
float_arr = arr.astype(np.float64)

In [20]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [21]:
float_arr.dtype

dtype('float64')

In [23]:
arr1 = np.array( [ [1,2,3],[4,5,6]], dtype=np.float64 ) 

In [24]:
arr2 = np.array( [ [7,8,9],[10,11,12]], dtype=np.float64 ) 

In [25]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [26]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [27]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [28]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [29]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [30]:
arr1 * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [31]:
arr1 ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [32]:
names = np.array(["pyo", "sunyoung", "psy", "pyo", "sunyoung", "sunny", "sunyoung"])
data = np.random.randn(7,4) 

In [33]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [34]:
data

array([[-0.35604946, -0.68247719,  0.21906893, -0.20849289],
       [-0.88658383, -1.0257245 , -0.08762142, -1.14390241],
       [ 0.36640728, -0.06279327,  1.33231349,  0.22282106],
       [ 0.0265502 , -2.00165113,  0.17001774,  0.03452415],
       [-1.05478211,  0.6928064 , -1.03974649, -0.9663121 ],
       [-0.54000937,  0.78052976,  0.84542728,  0.04533268],
       [ 0.56962483, -3.21695485, -1.7406435 ,  0.26510096]])

In [35]:
names == 'sunyoung'

array([False,  True, False, False,  True, False,  True], dtype=bool)

In [36]:
data[names == 'sunyoung', : ] 

array([[-0.88658383, -1.0257245 , -0.08762142, -1.14390241],
       [-1.05478211,  0.6928064 , -1.03974649, -0.9663121 ],
       [ 0.56962483, -3.21695485, -1.7406435 ,  0.26510096]])

In [37]:
data[names == 'pyo', : ] 

array([[-0.35604946, -0.68247719,  0.21906893, -0.20849289],
       [ 0.0265502 , -2.00165113,  0.17001774,  0.03452415]])

In [38]:
data[(names == 'sunyoung' ) | (names == 'pyo')] 

array([[-0.35604946, -0.68247719,  0.21906893, -0.20849289],
       [-0.88658383, -1.0257245 , -0.08762142, -1.14390241],
       [ 0.0265502 , -2.00165113,  0.17001774,  0.03452415],
       [-1.05478211,  0.6928064 , -1.03974649, -0.9663121 ],
       [ 0.56962483, -3.21695485, -1.7406435 ,  0.26510096]])

In [39]:
data[:, 3] 

array([-0.20849289, -1.14390241,  0.22282106,  0.03452415, -0.9663121 ,
        0.04533268,  0.26510096])

In [40]:
data[:, 3] < 0

array([ True,  True, False, False,  True, False, False], dtype=bool)

In [41]:
data[ data[:, 3] < 0, : ] 

array([[-0.35604946, -0.68247719,  0.21906893, -0.20849289],
       [-0.88658383, -1.0257245 , -0.08762142, -1.14390241],
       [-1.05478211,  0.6928064 , -1.03974649, -0.9663121 ]])

In [42]:
data[ data[:, 3] < 0, : ] =0

In [43]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.36640728, -0.06279327,  1.33231349,  0.22282106],
       [ 0.0265502 , -2.00165113,  0.17001774,  0.03452415],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.54000937,  0.78052976,  0.84542728,  0.04533268],
       [ 0.56962483, -3.21695485, -1.7406435 ,  0.26510096]])

In [44]:
# 파이썬 연산 테스트

# 마크다운1
## 마크다운2
### 마크다운3

- 리스트1
- 리스트2
- 리스트3

* 리스트1
* 리스트2
* 리스트3

In [45]:
"""여러줄의
문자열로
설명을 추가"""

'여러줄의\n문자열로\n설명을 추가'

## 벡터 연산 테스트

In [46]:
# 파이썬
a = [1,2]
b = [3,4] 
print(a+b) 

[1, 2, 3, 4]


In [47]:
# Numpy
a = np.array([1,2]) 
b = np.array([3,4]) 
print(a+b) 

[4 6]


In [48]:
arr = np.array([1,2,3,4,5])
arr * 2

array([ 2,  4,  6,  8, 10])

In [50]:
a = np.array([1,2,3,4,5]) 
b = np.array([6,7,8,9,10]) 

In [51]:
print( sum(a*b)) 

130


In [53]:
a = np.array([1,2,3,4]) 
b = np.array([3,4]) 
print(a+b) 
# 차원이 다르면 연산이 수행 되지 않음(에러)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [54]:
(1,2,3) + (4,5,6)

(1, 2, 3, 4, 5, 6)